version: '3.8'
services:
  certbot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: maskawanian/certbot-hetzner-stored-in-github
    working_dir: /
    container_name: certbot-domain
    restart: always
    environment:
      - CERTIFICATE_DOMAIN=
      - EMAIL_ADDR=
      - HETZNER_API_KEY=
      - GIT_URL=
      - KEYPAIR_PRIVATE_BASE64=